Repository DevDo-404Found/Devdo_Server, pull requests merged in 2025-08, with the labels that each got.

#22 [Feat/#21] - community 상세 조회 조회수 기능 추가
  DevDo/build.gradle
  DevDo/src/main/java/com/devdo/community/controller/CommunityController.java
  DevDo/src/main/java/com/devdo/community/entity/Community.java
  DevDo/src/main/java/com/devdo/community/service/CommunityService.java
Labels: Feature

#28 [Fix/#25] - Cookie 설정 변경
  DevDo/src/main/java/com/devdo/global/oauth2/AuthLoginService.java
  DevDo/src/main/resources/application.yml
Labels: Fix

#29 [Fix/#25] - cors 설정 추가
  DevDo/src/main/java/com/devdo/global/config/SecurityConfig.java
Labels: Fix

#34 [Feat] 2차 개발 완료
  DevDo/src/main/java/com/devdo/ai/controller/AiController.java
  DevDo/src/main/java/com/devdo/ai/controller/dto/AiRequestDto.java
  DevDo/src/main/java/com/devdo/ai/service/AiService.java
  DevDo/src/main/java/com/devdo/common/error/ErrorCode.java
  DevDo/src/main/java/com/devdo/common/error/SuccessCode.java
  DevDo/src/main/java/com/devdo/community/controller/CommunityController.java
  DevDo/src/main/java/com/devdo/community/controller/dto/response/CommunityAllResponseDto.java
  DevDo/src/main/java/com/devdo/community/controller/dto/response/CommunityDetailResponseDto.java
  DevDo/src/main/java/com/devdo/community/entity/Community.java
  DevDo/src/main/java/com/devdo/community/service/CommunityService.java
  DevDo/src/main/java/com/devdo/global/config/SecurityConfig.java
  DevDo/src/main/java/com/devdo/like/api/LikeController.java
  DevDo/src/main/java/com/devdo/like/application/LikeService.java
  DevDo/src/main/java/com/devdo/like/domain/Like.java
  DevDo/src/main/java/com/devdo/like/domain/repository/LikeRepository.java
  DevDo/src/main/java/com/devdo/member/domain/Member.java
  DevDo/src/main/java/com/devdo/node/controller/NodeController.java
  DevDo/src/main/java/com/devdo/node/controller/dto/request/NodeCreateRequestDto.java
  DevDo/src/main/java/com/devdo/node/controller/dto/response/NodeDetailResponseDto.java
  DevDo/src/main/java/com/devdo/node/controller/dto/response/NodeResponseDto.java
  DevDo/src/main/java/com/devdo/node/entity/Node.java
  DevDo/src/main/java/com/devdo/node/entity/NodeColor.java
  DevDo/src/main/java/com/devdo/node/entity/NodeShape.java
  DevDo/src/main/java/com/devdo/node/repository/NodeRepository.java
  DevDo/src/main/java/com/devdo/node/service/NodeService.java
  DevDo/src/main/java/com/devdo/nodepage/controller/NodePageController.java
  DevDo/src/main/java/com/devdo/nodepage/controller/dto/request/NodePageRequestDto.java
  DevDo/src/main/java/com/devdo/nodepage/controller/dto/response/NodePageResponseDto.java
  DevDo/src/main/java/com/devdo/nodepage/entity/NodePage.java
  DevDo/src/main/java/com/devdo/nodepage/repository/NodePageRepository.java
  DevDo/src/main/java/com/devdo/nodepage/service/NodePageService.java
  DevDo/src/main/java/com/devdo/roadmap/controller/RoadmapController.java
  DevDo/src/main/java/com/devdo/roadmap/controller/dto/request/RoadmapRequestDto.java
  DevDo/src/main/java/com/devdo/roadmap/controller/dto/response/RoadmapResponseDto.java
  DevDo/src/main/java/com/devdo/roadmap/entity/Roadmap.java
  DevDo/src/main/java/com/devdo/roadmap/repository/RoadmapRepository.java
  DevDo/src/main/java/com/devdo/roadmap/service/RoadmapService.java
  DevDo/src/main/resources/application.yml
Labels: Feature

#35 [Refactor/#14] comment refactoring
  DevDo/src/main/java/com/devdo/comment/api/CommentController.java
  DevDo/src/main/java/com/devdo/comment/api/dto/response/CommentInfoResDto.java
Labels: Refactor

#37 [Fix/#19] - 소문자 오타 수정
  .github/workflows/deploy.yml
  DevDo/src/main/java/com/devdo/global/oauth2/AuthLoginService.java
  DevDo/src/main/resources/application.yml
Labels: Fix
